### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Choudhury711** [conradyeung/sns-cart#1]
![capture](https://user-images.githubusercontent.com/25700563/28763281-c6af1bf8-758a-11e7-8119-6df65ae4b72f.PNG)
pLEASE HELP ME!!!!!!!

**Comment by Choudhury711** [comment]
![capture](https://user-images.githubusercontent.com/25700563/28851611-d6deeb30-76f1-11e7-9c71-b5e990787713.PNG)
Whats the problem here?? PLEASE HELP PLEASE!!!!!!!!

**Comment by conradyeung** [comment]
there are some parameters that you have to fill in on your own, I don't provide any support as the script is not complete and you have to know what it's doing to know how to use it.
